import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { getAttendanceReport } from '../models/attendanceModel.js';
import { findUserById } from '../models/userModel.js';
import { httpError } from '../utils/httpError.js';

const validStatuses = ['Present', 'Absent', 'Late'];

function normalizeValue(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function parseFilters(query) {
  const rawFacultyId = query.facultyId ?? query.faculty ?? '';
  const facultyIdValue = normalizeValue(rawFacultyId);
  const facultyId = facultyIdValue ? Number(facultyIdValue) : undefined;

  const filters = {
    student: normalizeValue(query.student),
    department: normalizeValue(query.department),
    facultyId,
    subject: normalizeValue(query.subject),
    date: normalizeValue(query.date),
    dateFrom: normalizeValue(query.dateFrom),
    dateTo: normalizeValue(query.dateTo),
    status: normalizeValue(query.status)
  };

  if (facultyIdValue && Number.isNaN(facultyId)) {
    throw httpError(400, 'facultyId must be a valid number.');
  }

  if (filters.status && !validStatuses.includes(filters.status)) {
    throw httpError(400, 'Invalid attendance status filter.');
  }

  ['date', 'dateFrom', 'dateTo'].forEach((key) => {
    if (filters[key] && Number.isNaN(Date.parse(filters[key]))) {
      throw httpError(400, `Invalid date format for ${key}. Use YYYY-MM-DD.`);
    }
  });

  if (filters.dateFrom && filters.dateTo && new Date(filters.dateFrom) > new Date(filters.dateTo)) {
    throw httpError(400, 'dateFrom cannot be later than dateTo.');
  }

  return filters;
}

export function getReportData(query) {
  const filters = parseFilters(query);
  const data = getAttendanceReport(filters);
  return { total: data.length, data };
}

function formatFilterLine(filters) {
  const applied = [];

  if (filters.dateFrom) applied.push(`From: ${filters.dateFrom}`);
  if (filters.dateTo) applied.push(`To: ${filters.dateTo}`);
  if (filters.department) applied.push(`Department: ${filters.department}`);
  if (filters.facultyId) applied.push(`Faculty ID: ${filters.facultyId}`);
  if (filters.student) applied.push(`Student: ${filters.student}`);
  if (filters.subject) applied.push(`Subject: ${filters.subject}`);
  if (filters.status) applied.push(`Status: ${filters.status}`);

  return applied.length ? applied.join(' • ') : 'None';
}

function formatDate(dateStr) {
  if (!dateStr) return '';
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const parts = dateStr.split('-');
  if (parts.length !== 3) return dateStr;
  const [y, m, d] = parts;
  return `${parseInt(d)} ${months[parseInt(m) - 1]} ${y}`;
}

export async function generatePdfReport(query, user) {
  const filters = parseFilters(query);
  const reportRows = getAttendanceReport(filters);

  let generatedBy = 'Unknown';
  if (user && user.id) {
    const profile = findUserById(user.id);
    if (profile) {
      generatedBy = `${profile.fullName} (${profile.role})`;
    }
  }

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      layout: 'landscape',
      margin: 40
    });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const leftMargin = 40;
    const bottomY = pageHeight - 35;

    // Title
    doc.fontSize(18).fillColor('#1e3a5f').text(
      'Student Attendance Monitoring and Analytics System',
      { align: 'center' }
    );
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor('#334155').text('Attendance Report', { align: 'center' });
    doc.moveDown(0.6);

    // Separator
    doc.moveTo(leftMargin, doc.y).lineTo(pageWidth - 40, doc.y).stroke('#cbd5e1');
    doc.moveDown(0.6);

    // Metadata
    const metaY = doc.y;
    const metaFontSize = 9;
    doc.fontSize(metaFontSize).fillColor('#475569');
    doc.text(`Generated Date: ${formatDate(new Date().toISOString().split('T')[0])}`, leftMargin, metaY);
    doc.text(`Generated By: ${generatedBy}`, leftMargin + 220, metaY);
    doc.text(`Total Records: ${reportRows.length}`, leftMargin + 480, metaY);
    doc.moveDown(0.5);
    doc.text(`Selected Filters: ${formatFilterLine(filters)}`, leftMargin, doc.y);
    doc.moveDown(0.5);

    // Separator
    doc.moveTo(leftMargin, doc.y).lineTo(pageWidth - 40, doc.y).stroke('#cbd5e1');
    doc.moveDown(0.5);

    const headerStartY = doc.y;

    // Column definitions
    const columns = [
      { label: 'Date', width: 85, align: 'left' },
      { label: 'Student', width: 165, align: 'left' },
      { label: 'Department', width: 115, align: 'left' },
      { label: 'Faculty', width: 125, align: 'left' },
      { label: 'Subject', width: 105, align: 'left' },
      { label: 'Status', width: 68, align: 'center' },
      { label: 'Remarks', width: 98, align: 'left' }
    ];

    const totalTableWidth = columns.reduce((s, c) => s + c.width, 0);
    const startX = leftMargin;
    const cellPad = 4;
    const cellFontSize = 8;
    const minRowH = 18;
    const headerH = 20;

    function drawHeader(y) {
      doc.rect(startX, y, totalTableWidth, headerH).fill('#f1f5f9');
      let x = startX;
      columns.forEach((col) => {
        doc.rect(x, y, col.width, headerH).stroke('#cbd5e1');
        doc.font('Helvetica-Bold').fontSize(cellFontSize).fillColor('#0f172a')
          .text(col.label, x + cellPad, y + cellPad, {
            width: col.width - cellPad * 2,
            align: col.align
          });
        x += col.width;
      });
      return y + headerH;
    }

    function calcRowHeight(values) {
      let maxH = minRowH;
      columns.forEach((col, i) => {
        const textH = doc.heightOfString(values[i] || '', {
          width: col.width - cellPad * 2,
          fontSize: cellFontSize
        });
        maxH = Math.max(maxH, textH + cellPad * 2);
      });
      return Math.max(minRowH, Math.ceil(maxH));
    }

    function drawRow(y, values, isEven) {
      const h = calcRowHeight(values);

      if (y + h > bottomY) {
        doc.addPage({ layout: 'landscape' });
        y = 40;
        y = drawHeader(y);
      }

      if (isEven) {
        doc.rect(startX, y, totalTableWidth, h).fill('#f8fafc');
      }

      let x = startX;
      columns.forEach((col, i) => {
        doc.rect(x, y, col.width, h).stroke('#cbd5e1');
        const textColor = i === 5 ? (
          values[i] === 'Present' ? '#059669' :
          values[i] === 'Absent' ? '#dc2626' :
          values[i] === 'Late' ? '#d97706' : '#334155'
        ) : '#334155';
        doc.font('Helvetica').fontSize(cellFontSize).fillColor(textColor)
          .text(values[i] || '', x + cellPad, y + cellPad, {
            width: col.width - cellPad * 2,
            align: col.align
          });
        x += col.width;
      });

      return y + h;
    }

    // Draw initial header
    let yPos = drawHeader(headerStartY);

    // Draw data rows
    if (reportRows.length === 0) {
      doc.font('Helvetica').fontSize(10).fillColor('#64748b')
        .text('No records match the current filters.', startX, yPos + 10);
    } else {
      reportRows.forEach((row, i) => {
        const values = [
          formatDate(row.attendanceDate),
          row.studentName,
          row.facultyDepartment || 'N/A',
          row.facultyName,
          row.subject,
          row.status,
          row.remarks || ''
        ];
        yPos = drawRow(yPos, values, i % 2 === 0);
      });
    }

    // Footer and page numbers
    const totalPages = doc.bufferedPageRange().count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      doc.fontSize(7).fillColor('#94a3b8')
        .text('Generated by Student Attendance Monitoring and Analytics System', leftMargin, pageHeight - 25, { align: 'center' });
      doc.text(`Page ${i + 1} of ${totalPages}`, leftMargin, pageHeight - 15, { align: 'center' });
    }

    doc.end();
  });
}

export async function generateExcelReport(query) {
  const filters = parseFilters(query);
  const reportRows = getAttendanceReport(filters);
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Attendance Report');

  sheet.columns = [
    { header: 'Student ID', key: 'studentId', width: 12 },
    { header: 'Student Name', key: 'studentName', width: 24 },
    { header: 'Department', key: 'department', width: 18 },
    { header: 'Faculty', key: 'facultyName', width: 22 },
    { header: 'Subject', key: 'subject', width: 18 },
    { header: 'Date', key: 'attendanceDate', width: 14 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'Remarks', key: 'remarks', width: 28 }
  ];

  sheet.addRows(
    reportRows.map((row) => ({
      studentId: row.studentId,
      studentName: row.studentName,
      department: row.facultyDepartment || 'N/A',
      facultyName: row.facultyName,
      subject: row.subject,
      attendanceDate: row.attendanceDate,
      status: row.status,
      remarks: row.remarks || ''
    }))
  );

  sheet.getRow(1).font = { bold: true };

  return workbook.xlsx.writeBuffer();
}
